name: CI

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install
          sudo apt-cache search sqlite
          sudo apt install sqlite3
          git submodule update --init
          wget https://sqlite.org/2021/sqlite-autoconf-3340100.tar.gz
          tar -xvf sqlite-autoconf-3340100.tar.gz && cd sqlite-autoconf-3340100
          ./configure
          make
          sudo make install
          export PATH="/usr/local/lib:$PATH"
          sqlite3 --version
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make all
      - name: Test daemon
        run: |
          cd build
          ./test_daemon
